### ISSUE TITLE
Framework / tech standard to follow

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/DEVSCHEDULER#1]
Copast from [here](https://github.com/ferdinalcandra/fc/issues/12)

Technology :
spring boot 2.x + gradle (via start.spring.io), latest : OK
JDK 15 via OpenJDK : OK
 
 - Spring web, JPA via hibernate, Spring RabbitMQ, lombok (spring boot stack untuk development microservice) : 
    + **Pakai starter-web, tapi kenapa masih ada dependency ke javax servlet?**
    + **sudah pakai starter-web, untuk serialize/deserialize JSON tolong gunakan Jackson ObjectMapper, jangan pakai `org.json:json:20201115` ... too much work hanya untuk json conversion**  
     + **jcifs itu dead library, ga ada patch sejak bertahun2 lalu. Kenapa masih dipakai ya. Kalau untuk FTP, coba gunakan apache commns net**.
 - Spring Rest repositories diperbolehkan untuk speed up CRUD API : **unused**
 - Springdoc untuk create swagger : **belum ada**
 - openfeign (untuk web client, hindari RestTemplate atau low-level client untuk reduce code) : **masih pakai RestTemplate, gunakan OpenFeign whenever possible. Dengan openfeign, hit API bisa di-retry menggunakan resilience4j. Tolong di-combine**
 - resilience4j (untuk mekanisme resilisent API (e.g. retry / circuit breaker)) : **see above, combine dengan openfeign**
 - codecentric admin client (for monitoring) : **belum ada**
 - sleuth : **belum ada, low priority**
 - Unit test via JUnit : coverage target 60% : **belum ada**
  
In case additional yech required :
 - freemarker (kalau perlu templating engine)
 - Quartz with persistence (e.g. database) scheduler, kalau perlu scheduler complex. Kalau schedulernya simple, silakan gunakan spring @Scheduled dengan durais di-externalize ke file .yml terpisah
 
Architecture & source code organization:
 - Adopt hexagonal architecture & CQS. Contact timo untuk detail template nya:
   + please arrange discussion time, ini kita adopt CQS, tapi foldering / packaging nya belum adopt. Please contact me asap untuk detialnya
    + conf folder bukan bagian dari source code (not part package `id.co.bfi.dmsuploadscheduler` tapi source folder tersendiri.

**Comment by timpamungkasudemy** [comment]
Pakai springdoc please, jangan springfox buat swagger.
Springfox itu banyak bugnya

**Comment by timpamungkasudemy** [comment]
CQS nya tolong ikutin [struktur ini](https://gitlab.com/bfi/architecture/listener-chassis/-/tree/master/src/main/java/id/co/bfi/listenerchassis) 
  
Doc nya [disini](https://docs.google.com/presentation/d/1fE3GIBkuumnt5tmXAODlLFqbd6LuZryExCPk1XyxqmM/edit) slide 66
  
Reminder lagi, please contact me untuk arrange kalau bingung bacanya

**Comment by timpamungkasudemy** [comment]
Sudah pakai boot, kenapa masih manual dependency ke spring-aspect?

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by ferdinalcandra** [comment]
kita masih in progress yah Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
Pak @timpamungkas , mohon bantuannya untuk diulas kembali.

Branch : scheduler-branch

**Comment by timpamungkasudemy** [comment]
Dependency ok, just need update ke spring boot 2.4.3

**Comment by timpamungkas** [comment]
Tapi struktur CQS nya belum dijalankan

**Comment by ferdinalcandra** [comment]
- dependency javax servlet dan spring aspect sudah dihapus

- library jcifs sudah diganti menggunakan apache commons vfs (untuk ambil file dari share folder)

- resilience4j retry : digunakan didalam class DctmRestService Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
- jUnit script : sudah ditambahkan di resource java/test

- dependency codecentric admin client dan sleuth sudah ditambahkan di build.gradle Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
> * dependency javax servlet dan spring aspect sudah dihapus
> * library jcifs sudah diganti menggunakan apache commons vfs (untuk ambil file dari share folder)
> * resilience4j retry : digunakan didalam class DctmRestService Pak @timpamungkas

Pak @timpamungkas @timpamungkasudemy 

kita menggunakan apache commons vfs2 untuk ambil file dari shared folder, ternyata sering error dan tidak bisa keambil file-nya

error : 
[Could not read from "file:////10.88.88.141/dms_req_upload/4642725a0b8c4362b555965dc4887d6e.xlsx" because it is not a file., InputStream must have > 0 bytes]

![1](https://user-images.githubusercontent.com/74760989/111126573-6c6b4700-85a5-11eb-9c53-a5362fedaf52.jpeg)
https://commons.apache.org/proper/commons-vfs/filesystems.html
masih belum directly supported dengan vfs

![2](https://user-images.githubusercontent.com/74760989/111126638-7f7e1700-85a5-11eb-87a9-ec95f817a3af.jpeg)
https://commons.apache.org/proper/commons-vfs/testing.html
dan belum tested juga

**Comment by timpamungkas** [comment]
apakah ada alternatif lain @ferdinalcandra ?

**Comment by ferdinalcandra** [comment]
Pak @timpamungkas

kalau kita menggunakan JCIFS NG
https://mvnrepository.com/artifact/eu.agno3.jcifs/jcifs-ng

update terakhir July 2020
gimana Pak @timpamungkas ?

**Comment by timpamungkas** [comment]
ok coba aja @ferdinalcandra

**Comment by ferdinalcandra** [comment]
makasih Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
apache commons vfs diganti menggunakan jcifs-ng

spring boot update menjadi versi 2.4.3

**Comment by ferdinalcandra** [comment]
Pak @timpamungkas 

apache commons vfs diganti menggunakan jcifs-ng

spring boot update menjadi versi 2.4.3

**Comment by timpamungkas** [comment]
closed

**Comment by timpamungkas** [comment]
reopen for code coverage, tolong paste screenshot code coverage (min 60%) dan status run nya (% passed / failed)  

Thanks

**Comment by ferdinalcandra** [comment]
![image](https://user-images.githubusercontent.com/74760989/112783267-261fe880-9079-11eb-867d-a9b2124f581e.png)

![image](https://user-images.githubusercontent.com/74760989/112783280-2e782380-9079-11eb-81e5-a1b52462f845.png)

Pak @timpamungkas

**Comment by timpamungkas** [comment]
closed
