### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by timpamungkasudemy** [ferdinalcandra/DEVSCHEDULER#10]
Ini `Ms` di `MsDataDbConfig` maksudnya `Microsoft`?
ADa database non microsoft sql server kah?

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by ferdinalcandra** [comment]
Consistent Naming : MsDataSourceConfig diubah menjadi DataSourceConfig, prefix spring.datasource menjadi documentum.datasource Pak @timpamungkasudemy

**Comment by timpamungkasudemy** [comment]
closed
