### ISSUE TITLE
Externalize query

### ISSUE THREAD

**Issue by timpamungkasudemy** [ferdinalcandra/DEVSCHEDULER#11]
JPQL di repository belum di externalize, masih di hardcode di .java nya

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by ferdinalcandra** [comment]
Externalize Query : sudah diubah menggunakan Hibernate Criteria Pak @timpamungkasudemy

**Comment by timpamungkasudemy** [comment]
works sih, tapi jadi lebih complex. Kenapa ga pake [cara ini](https://stackoverflow.com/questions/46060590/externalize-query-in-spring-boot-application)

**Comment by timpamungkas** [comment]
I know, gw tahu hibernate criteria.  
Hanya saja pakai itu lebih complex, karena biasanya dipakai untuk build query based on logic. Sementara yg sekarang dipakai itu flat, ga ada logic untuk build query nya.  
Worry aja karena jadi overkill, yang native query bisa (tinggal di externalize), tp skrg di move ke Hibernate Criteria.  
  
Pertimbangannya apa ya?

**Comment by timpamungkas** [comment]
cmiiw even ini sebenarnya jg bisa 

```java
	public List<DocumentEntity> getDocumentList() {
		CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
		CriteriaQuery<DocumentEntity> criteriaQuery = criteriaBuilder.createQuery(DocumentEntity.class);
		
		Root<DocumentEntity> root = criteriaQuery.from(DocumentEntity.class);
		
		criteriaQuery.orderBy(criteriaBuilder.asc(root.get("createdDate")));
		
		return entityManager.createQuery(criteriaQuery).getResultList();
	}
```

diubah dengan JPA repo standar, which basically elu bahkan ga tulis query.

```
public interface MyRepo extends JpaRepository<DocumentEntity, String> {
  List<DocumentEntity> findAllOrderByCreatedDateAsc();
}
```

**Comment by timpamungkas** [comment]
Bukan berarti harus ngubah. Just share pertimbangannya apa ya kenapa simple query jg langsung dihajar pake Criteria?

**Comment by ferdinalcandra** [comment]
sudah ditambahkan di /conf/META-INF/jpa-named-queries.properties, Pak @timpamungkas

**Comment by timpamungkas** [comment]
closed
