### ISSUE TITLE
JsonNode usage

### ISSUE THREAD

**Issue by timpamungkasudemy** [ferdinalcandra/DEVSCHEDULER#12]
Di beberapa line di `DctmFolderService` ada comment `test`, maksudnya apa ya?
Kemudian ini kenapa pakai `JsonNode`? Apakah struktur JSON nya dynamic, sehingga harus pakai JsonNode?
JsonNode itu kalau ga hati2 pakainya bisa bahaya karena strukturnya ga dikunci.

**Comment by timpamungkasudemy** [comment]
Contoh : https://www.baeldung.com/jackson-object-mapper-tutorial

Instead bikin semua di JsonNode kmudian parse manual dengan hardcodean dimana2, map otomatis.

Kalau memang satu endpoint bisa multiple structure (multiple request / multi response), silakan pakai JsonNode.

Tapi kalau satu endpoint, sttructure request/response nya fixed, pakai class sendiri untuk request dan response nya, map itu pakai Jackson

**Comment by timpamungkasudemy** [comment]
atau misalnya gini, sama2 hit endpoint x.com/api/abc , tapi responsenya bisa seperti ini:

jenis 1
```json
{
   "name":"Andi",
   "detail":"Just a regular String"
}
```

jenis 2
```json
{
   "name":"Andi",
   "detail":{
      "age":25,
      "gender":"male",
      "address":"xxxxx"
   }
}
```

Note di field `detail`, structure nya bisa beda walaupun endpoint nya sama. Nah disini mesti pake `JsonNode` buat parse, tapi harus handle kemungkinan2nya (apakah return simple string, atau structure tertentu)
```

**Comment by timpamungkasudemy** [comment]
Kl cm gini doang, untuk hit endpoint yang sama

````json
{
 "name" : "Andi",
 "detail" : "xxxx"
}
```

```json
{
 "name" : "Andi",
 "detail" : "xxxx",
 "gender" : "male",
 "date_of_birth" : "1990-02-21"
}
```

Itu ga dynamic namanya. Bikin aja satu class ginian

```java
@JsonIgnoreProperties(ignoreUnknown=true)
public class MyClass {
 private String name;
 private String detail;
 private String gender;
 private String date_of_birth;
}
```

Tar spring nya yang akan convert otomatis.


Anyway elu jg mungkin ga perlu ngetik class nya ya... coba google deh "json to java converter".

**Comment by timpamungkasudemy** [comment]
google aja spring rest api tutorial, banyak kok di inet

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by timpamungkasudemy** [comment]
Jangna pakai yang sekarang bikin `DctmRestRequest`,  `DctmRestDqlResponse`, `DctmRestResponse`.
Cara pakainya bukan gitu (bukan bikin satu generic class buat semua request, trus property dimapping manual).   
Coba lihat contoh di [comment](https://github.com/ferdinalcandra/DEVSCHEDULER/issues/12#issuecomment-789455077)
Untuk generic class, case penggunaannya beda lagi.

Bikin seperti ini misalnya untuk `DctmRestFolderService.createObject`

```java
public class DctmCreateObjectRequest {
  private String objectName;
  private String rObjectType;

  // getters & setters
}
```

```java
public ResponseEntity<String> createObject(String objectName, String objectType, String url)
			throws JsonMappingException, JsonProcessingException {
		var request = new DctmCreateObjectRequest ();
		request.setObjectName(objectName);
                request.setRObjectType(objectType);

		return dctmRestService.createObject(url, request));
	}
```

Di service

```java
public ResponseEntity<String> createObject(String url, DctmCreateObjectRequest  request) {
		return dctmRestClient.createObject(url, request);
	}
```

Di client
```java
ResponseEntity<String> createObject(@Param(value = "url") String url, @RequestBody DctmCreateObjectRequest  request);
```

----


Bedakan dengan request object untuk `generateFolderPathTest`.
```java
public class DctmGenerateFolderPathRequest {
  private String customerId;
  private String dctmBranchId;
  private String dctmLeadsId;
}
```

dst...

```

**Comment by timpamungkasudemy** [comment]
Hal yang sama berlaku jug auntuk response nya, **JANGAN** bikin satu class yang dipakai untuk semua!   
Melanggar coding practice ini : https://en.wikipedia.org/wiki/Single-responsibility_principle

  
  
Kalau mau bikin ygeneric, ada beda lagi caranya

**Comment by ferdinalcandra** [comment]
JsonNode : request / response sudah di mapping kedalam class DctmRestRequest, DctmRestResponse & DctmRestDqlResponse Pak @timpamungkasudemy

**Comment by timpamungkasudemy** [comment]
> JsonNode : request / response sudah di mapping kedalam class DctmRestRequest, DctmRestResponse & DctmRestDqlResponse Pak @timpamungkasudemy

See [ini](https://github.com/ferdinalcandra/DEVSCHEDULER/issues/12#issuecomment-797209773) dan [ini](https://github.com/ferdinalcandra/DEVSCHEDULER/issues/12#issuecomment-797210489)

**Comment by ferdinalcandra** [comment]
sudah dipisahkan masing-masing object untuk request & response Pak @timpamungkasudemy

**Comment by timpamungkas** [comment]
@ferdinalcandra

**Comment by ferdinalcandra** [comment]
object tersebut digunakan untuk ambil metadata, untuk cek versioning, define document type dan generate folder path based on document type Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
> object tersebut digunakan untuk ambil metadata, untuk cek versioning, define document type dan generate folder path based on document type Pak @timpamungkas

ini di call di DmsUploadService

**Comment by timpamungkas** [comment]
DmsUploadService not in call hierarchy

![image](https://user-images.githubusercontent.com/17508786/112108542-e96c7100-8be2-11eb-8325-69a2a5d92cd7.png)


![image](https://user-images.githubusercontent.com/17508786/112108586-fd17d780-8be2-11eb-8aec-59936636f859.png)

**Comment by timpamungkas** [comment]
yang untuk keperluan test, jangan dimasukkan ke src/main, pindahkan ke src/test. Biar ga ngotorin main folder nya

**Comment by timpamungkasudemy** [comment]
closed
