### ISSUE TITLE
Clean code di scheduler

### ISSUE THREAD

**Issue by timpamungkasudemy** [ferdinalcandra/DEVSCHEDULER#15]
method ini di `UploadDocHistoryService`

`public void processDmsReqUpload() throws SQLException, IOException {`

Ini dalam banget, ada 11 level `if`, dan panjang juga.
Refactor dengan service-action (see [here slide 66](https://docs.google.com/presentation/d/1fE3GIBkuumnt5tmXAODlLFqbd6LuZryExCPk1XyxqmM/edit#slide=id.g7e7465b9f7_0_30)) , sehingga lebih readable

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by timpamungkasudemy** [comment]
masih belum ikut cqs dan service-action pattern (see [slide 82 di sini](https://docs.google.com/presentation/d/1fE3GIBkuumnt5tmXAODlLFqbd6LuZryExCPk1XyxqmM/edit#slide=id.g6fed90dee9_0_574))

**Comment by ferdinalcandra** [comment]
sudah dipisahkan antara service dan action di package query Pak @timpamungkasudemy

**Comment by timpamungkas** [comment]
`DmsUploadService` ini command atau query? Ubah data tapi kok masuk query? @ferdinalcandra

**Comment by ferdinalcandra** [comment]
DmsUploadService saat proses akan call DmsUploadAction.

ubah data yg dimaksud disebelah mana yah Pak?

dan seharusnya disimpan di package apa yah Pak @timpamungkas ?

**Comment by timpamungkas** [comment]
Changing data (should be on command).  
Tolong crosscek terhadap sample code, tutorial, link yang sudah dibeirkan.  
Ini belum implement CQS.. baru QS aja
```

objectId = dmsUploadAction.doUpload(documentsList, i, uploadHistoryList, j, msg, objectId,
									dctmUploadRequest, dmsDocType, properties);
```

**Comment by timpamungkas** [comment]
Jalanin sonarlint / sonarqube deh buat check quality code elu @ferdinalcandra

**Comment by timpamungkasudemy** [comment]
closed
