### ISSUE TITLE
Quality control based on sonarqube

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/DEVSCHEDULER#19]
Struktur code nya sudah cukup lumayan, walaupun masih ada issue.
Speaking quality, ada 27 potential bug yang HARUS diperbaiki.
Untuk quality control, saya pakai sonarqube (default configuration).
Silakan cek juga. Download sendiri sonarqube nya di sonarqube.org

![image](https://user-images.githubusercontent.com/17508786/111860159-44e6f680-8978-11eb-8eb5-e266b26e9207.png)

Ada 100 code smell, fix yang blocker, critical, dan major
![image](https://user-images.githubusercontent.com/17508786/111860170-53351280-8978-11eb-82e6-0be0e706cda2.png)

**Comment by timpamungkas** [comment]
Bad quality code, please fix (based on sonarqube default config)

![image](https://user-images.githubusercontent.com/17508786/111860007-495edf80-8977-11eb-9451-a3179212facc.png)

**Comment by timpamungkas** [comment]
prioritize on bugfix please

**Comment by ferdinalcandra** [comment]
![image](https://user-images.githubusercontent.com/74760989/112783330-4c458880-9079-11eb-9ff8-08bbe620bd62.png)

Pak @timpamungkas

**Comment by timpamungkas** [comment]
closed
