### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/DEVSCHEDULER#3]
Most attributes are default (package-level). 
e.g.

```java
        @Autowired
	RestTemplate restTemplate;
```

Fix the encapsulation (private attrs for class-level attrs)

```java
        @Autowired
	private RestTemplate restTemplate;
```

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by timpamungkas** [comment]
MAsih package level di DataSourceConfig, RestTemplateConfig, DmsUploadScheduler, DctmDocumentsService, DctmUploadDocumentHistoryService

**Comment by ferdinalcandra** [comment]
encapsulation : sudah ditambahkan private di class access attrs, Pak @timpamungkas

**Comment by timpamungkas** [comment]
closed
