### ISSUE TITLE
Source code readability

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/DEVSCHEDULER#4]
Please format your source code (e.g. CTRL-SHIFT-F) on eclispse to make it more readable

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by timpamungkas** [comment]
klik kanan aja di src/main/java > source > format

**Comment by ferdinalcandra** [comment]
Source code readability : sudah di format (ctrl + shift + f) Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
source code readability : sudah dilakukan source -> format pada src/main/java Pak @timpamungkas

**Comment by timpamungkas** [comment]
solved
