### ISSUE TITLE
Document type

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/DEVSCHEDULER#5]
`UploadDocHistoryService.processDmsReqUpload` is too deep (7 level if??), which decrease readability

`String mimeType = uploadDocHistoryList.get(j).getDmsMimeType();`

Mime type pada waktu awalnya, diset dari mana ya?

**Comment by ferdinalcandra** [comment]
Mime type pada waktu awalnya, diset dari mana ya?

di set dari table temporary (dctm_upload_document_history)

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ? ini soal validasi mime nya ya

**Comment by timpamungkas** [comment]
still too long, ikuti CQS model, dan service-action. Service call banyak action. Lihat [slide ini](https://docs.google.com/presentation/d/1fE3GIBkuumnt5tmXAODlLFqbd6LuZryExCPk1XyxqmM/edit) slide 82

**Comment by ferdinalcandra** [comment]
Document type : mime type validation di class ShareFolderService method validateFile(), menggunakan apache tika Pak @timpamungkas

**Comment by ferdinalcandra** [comment]
sudah dipisahkan antara service dan action di package query Pak @timpamungkas

**Comment by timpamungkas** [comment]
> Document type : mime type validation di class ShareFolderService method validateFile(), menggunakan apache tika Pak @timpamungkas

belum pakai tika kok, elu masih bikin sendiri.

`ShareFolderAction.getMimeTypeFromFile` ini hapus aja. Kan gw udah minta pake tika aja, lebih terpercaya. Ga perlu bikin sendiri

Contoh

```java
var tika = new Tika();
var mimeType = tika.detect(bytes);
```

Beres dalam 1 line. Tlg optimize ya code samplenya, masukin itu tikanya ke class var, jgn local.

**Comment by ferdinalcandra** [comment]
kita menggunakan Tika Pak @timpamungkas cuma pake parser juga buat validate-nya

**Comment by timpamungkas** [comment]
![image](https://user-images.githubusercontent.com/17508786/112108383-b5914b80-8be2-11eb-8aec-7b1f7add57d8.png)

Codingan elu di atas, itu fungsinya `tika.detect`. Jangan reinvent the wheel

**Comment by ferdinalcandra** [comment]
cara tsb (tika.detect) sudah dilakukan, untuk format pdf dan jpg mime type nya cocok
tapi untuk format office tidak cocok
- word (docx) : application/x-tika-ooxml -> harusnya application/vnd.openxmlformats-officedocument.wordprocessingml.document
- excel (xlsx) : application/x-tika-ooxml -> harusnya application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

Pak @timpamungkas

**Comment by timpamungkas** [comment]
closed
