### ISSUE TITLE
ResilienceConfig

### ISSUE THREAD

**Issue by timpamungkasudemy** [ferdinalcandra/DEVSCHEDULER#8]
ini ga salah, 3000 attempt per 10 detik?
Berarti worst case scenario akan nyoba terus2an selama 30.000 detik (8 jam)?

```java
		return RetryConfig.custom().
		maxAttempts(3000).waitDuration(Duration.ofSeconds(10)).build();
```

**Comment by timpamungkasudemy** [comment]
Ini belum ada update @ferdinalcandra ?

**Comment by timpamungkasudemy** [comment]
closed

**Comment by ferdinalcandra** [comment]
ResilienceConfig : max attemp di set 3, wait duration 10000 (millisecond) parameter di application.yml Pak @timpamungkasudemy
